### PR TITLE
Add Optimole checkbox in wizard

### PR DESCRIPTION
**Pull request by arinaturcu**
Closes https://github.com/Codeinwp/optimole-service/issues/662.

- Add a checkbox in the wizard that if checked, going to the next step will install and activate Optimole.
- Replace text
- Replace the right top corner icon with an `X` one
- Remove the Otter banner from the wizard
- Change the style of the selected template

Screenshot 2023-02-15 at 21 55 10

### Test instructions
- The test instance must not have installed the plugin before for the wizard to show, or it can be simulated with `wp option update wpmm_fresh_install 1`
- If the Optimole checkbox is checked, and the `Continue` button is clicked, it should install and activate both Otter and Optimole
- If the Optimole checkbox is checked, and the `I don't want a template` button is clicked, it should install and activate just Optimole
- If the checkbox is unchecked it should behave like before.

### CODE REVIEW

**Review by selul — APPROVED** [review]
LGTM 🚀

**Comment by irinelenache** [comment]
@arinaturcu Tested and here is what i found:

- [ ] Maybe we can add the external link icon to the Otter and Optimole links https://vertis.d.pr/i/exdoeK Also the same in the Lightstart settings https://vertis.d.pr/i/Qzd6yq
- [ ] I'm getting a 500 error when i'm trying to import a template through the wizard https://vertis.d.pr/v/g2nWvE Also i'm getting a 500 error when i'm trying to import a template through Lightstart settings

The issues can be checked here:
```
 Admin area URL: https://soakpie.s1-tastewp.com/wp-admin 
 Username: irinel 
 Password: BfbKlIFetzQ 
```

**Comment by arinaturcu** [comment]
@selul Here I also updated the `@wordpress/eslint-plugin` version from `^12.9.0` to `^14.0.0` to fix this error:
```
error eslint-plugin-jsdoc@37.9.7: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^16 || ^17". Got "18.14.1"
```

Let me know it that's ok.

**Comment by selul** [comment]
@arinaturcu sure.

**Comment by irinelenache** [comment]
@arinaturcu Tested and the mentioned issues are fixed, thank you 🚀 

Something else that happens after the last commits:

- [ ] If i uncheck the **Optimole checkbox** and also use the **I don't want to use a template** button, i'm getting a console error and nothing happens https://vertis.d.pr/i/4dGZ6w

**Comment by arinaturcu** [comment]
Thanks @irinelenache 🚀 
Should be fixed now.

**Comment by irinelenache** [comment]
@arinaturcu Checked again and now everything's fine, thank you 🎉

**Pull request merged**
