### PR TITLE
Managed status from the network dashboard

### LINKED ISSUE #295: Enable/disable maintenance mode for sub-sites from one place
Could we add an option to enable/disable the maintenance mode for subsites from one place instead of accessing and modifying each subsite?

Suggested [here](https://wordpress.org/support/topic/images-still-accessible-and-multi-site/).

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #295

### CODE REVIEW

**Comment by irinelenache** [comment]
@girishpanchal30 I think this is the new PR for the feature and we'll close [this one](https://github.com/Codeinwp/wp-maintenance-mode/pull/298). Let me know if i'm wrong. Here are my findings:

- [ ] Before selecting anything in the network dashboard, there were some notices next to the **activated for all sites/deactivated for all sites** options https://vertis.d.pr/i/iAHynU
- [ ] The setting doesn't work for all subsites, it only disables the root website's setting but does nothing for the others https://vertis.d.pr/v/oAClqU

You can check on this instance:
```
URL: https://calm-cat-guca.vertisite.cloud
Username: gigegexalo1538
Password: UiOokgaes8DNXdxVjf51
```

**Comment by girishpanchal30** [comment]
@irinelenache I've fixed the mentioned issue with the most recent commit and closed the previous PR.

**Comment by girishpanchal30** [comment]
@irinelenache

>  I think we should deactivate the mode on all subsites and have the individual option disabled, like we do when it's activated

Done


> After adding the add_filter( 'wpmm_manage_from_network_dashboard', '__return_false' ); filter to functions.php

It seems working fine now, please test with the latest commit.

**Comment by girishpanchal30** [comment]
@irinelenache Let's add the `network mode` enable/disable option instead of the filter. Please re-check with the latest commit and let me know if you have any other suggestions.
Ref: https://tinyurl.com/2h66o42r

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 

- [ ] When i first open the Lightstart network settings, there will be a notice next to the **Enable network mode** setting https://vertis.d.pr/i/Jq1Fbv
- [ ] If the network status is **Activated for all sites** and i disable the **network mode**, the individual status for every subsite will stay the same when i try to change it https://vertis.d.pr/v/HGiNG4

**Comment by girishpanchal30** [comment]
@irinelenache Fixed both issue, Please check with the latest commit.

**Pull request merged**
