### PR TITLE
Add option to enable/disable maintenance mode from one place

### LINKED ISSUE #295: Enable/disable maintenance mode for sub-sites from one place
Could we add an option to enable/disable the maintenance mode for subsites from one place instead of accessing and modifying each subsite?

Suggested [here](https://wordpress.org/support/topic/images-still-accessible-and-multi-site/).

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #295

### CODE REVIEW

**Comment by girishpanchal30** [comment]
@selul

I have made some changes to make it compatible with the latest version. Now ticket is `Ready for testing`.
May be QA team find out the issues. @irinelenache Can you please do a retest?

Thanks

**Comment by irinelenache** [comment]
@selul @girishpanchal30 
I think we should make a clear decision about how this feature should work because now there are some issues happening:
- Now on the network dashboard, i have the option to [import a template](https://vertis.d.pr/fXzG2Z) even if pages are not available for this dashboard. If i try to import one and see the page, i'll get redirected to the main website's dashboard https://vertis.d.pr/l9bTxm

- If i enable the **Activated on all sites** setting on the [network dashboard ](https://vertis.d.pr/IcYSkC), the individual setting will still appear as **Deactivated** on every subsite and in frontend i'm seeing the old design of the maintenance page https://vertis.d.pr/MPpKY1 . When i switch the status to **Activated** for every subsite in particular, i'll see the selected maintenance pages in frontend. After that, if i go again to the network dashboard and select the status as  **Deactivated for all sites**, the maintenance pages will still be visible in frontend for the sites

My idea is to just have two simple controls on the network dashboard:
1. Yes/No option asking the user if he wants to manage the status from one place
2. Status Activated/Deactivated (if the user selected **yes** for the first one)

Let me know your thoughts on this 🙏 

Also, you can check the issues i mentioned on this instance:
```
URL : https://multisite.s.themeisle.com/
Username : multisite
Password : RC8O3Z6M
```

**Comment by girishpanchal30** [comment]
@irinelenache

> My idea is to just have two simple controls on the network dashboard:
1. Yes/No option asking the user if he wants to manage the status from one place
2. Status Activated/Deactivated (if the user selected yes for the first one)

The idea is very pretty and simple. We can ask Yes/No when the plugin is activated on the network site.

@selul what do you think?

Thanks

**Comment by girishpanchal30** [comment]
@irinelenache

I've implement your idea in this PR, please check with the PR build zip.

> 1. Yes/No option asking the user if he wants to manage the status from one place

For this option, I've chosen to add a filter so the user can disable this feature.

`add_filter( 'wpmm_manage_from_network_dashboard', '__return_false' );`

Add this filter in your active theme **functions.php** file.

> Status Activated/Deactivated (if the user selected yes for the first one)

https://tinyurl.com/2m6trvnc

Please check and let me know if you have any other suggestions as well.

Thanks

**Pull request closed without merging**
