### PR TITLE
Fixed compatibility issue with WP Optimize

### LINKED ISSUE #404: Conflict with WP-Optimize
### Description

A user reported that a fatal error occurs when Wp-Optimize and Lightstart are activated and you setup a coming soon/maintenance page. The issue appears when creating the page from the setup wizard, as well as when it is created later on, from LightStart -> Design. It lets you select the desired template for the page from the predesigned ones, but after the last step, when you can choose to go to the page or to go to the settings, the fatal error occurs. I am able to replicate the issue on my instance.

### Step-by-step reproduction instructions

1. Install WP-Optimize
2. Install LightStart
3. Go through the setup wizard and create a page
4. Check the error after the last step of the wizard

### Screenshots, screen recording, code snippet or Help Scout ticket

Capture

Reported [here](https://wordpress.org/support/topic/conflict-with-wp-optimize-5/)

### Environment info

_No response_

### Is the issue you are reporting a regression

No

### PR DESCRIPTION
**Pull request by girishpanchal30**
Close #404

### CODE REVIEW

**Review by HardeepAsrani — CHANGES_REQUESTED** [review]
As far as I remember, the pages were kept private to avoid non-admins seeing them when they were published: https://github.com/Codeinwp/wp-maintenance-mode/commit/73707a4777dfb54f4fb7932b664f5347c8134927

It will add an issue where if you import a template and don't publish it, the homepage will start redirect and page won't load.

The same won't with the existing version.

**Comment by girishpanchal30** [comment]
@HardeepAsrani Thank you for checking! I've got the solution, can you please check with the latest commit when you have a moment?

**Review by HardeepAsrani — APPROVED** [review]

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and everything's fine on my end 👍

**Comment by vytisbulkevicius** [comment]
@girishpanchal30, can you check this conflict? Thanks!

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Fixed

**Pull request merged**
